# Generated by Django 2.2 on 2019-04-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('sex', models.IntegerField(default=1)),
                ('tel', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=20, null=True, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('create_time', models.CharField(max_length=100)),
                ('is_del', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dir_name', models.CharField(max_length=50)),
                ('create_time', models.CharField(max_length=50)),
                ('is_del', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete='PROTECT', to='app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=50)),
                ('create_time', models.CharField(max_length=50)),
                ('is_del', models.BooleanField(default=False)),
                ('corpus', models.ForeignKey(on_delete='PROTECT', to='app.Corpus')),
            ],
        ),
    ]
