# Generated by Django 2.2 on 2019-04-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='love',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SonArt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('send_user_name', models.CharField(max_length=50)),
                ('art_time', models.CharField(max_length=20)),
                ('is_del', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete='PROTECT', to='app.User')),
            ],
        ),
        migrations.CreateModel(
            name='FatherArt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('art_time', models.CharField(max_length=20)),
                ('is_del', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete='PROTECT', to='app.Book')),
                ('user', models.ForeignKey(on_delete='PROTECT', to='app.User')),
            ],
        ),
    ]
