# Generated by Django 2.2 on 2019-04-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190421_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='look',
            field=models.IntegerField(default=0),
        ),
    ]
