# Generated by Django 2.2 on 2019-04-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_book_look'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='LikeBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.CharField(max_length=20)),
                ('is_del', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete='PROTECT', to='app.Book')),
                ('user', models.ForeignKey(on_delete='PROTECT', to='app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('be_focus_user', models.IntegerField()),
                ('create_time', models.CharField(max_length=20)),
                ('is_del', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete='PROTECT', to='app.User')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.CharField(max_length=20)),
                ('is_del', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete='PROTECT', to='app.Book')),
                ('user', models.ForeignKey(on_delete='PROTECT', to='app.User')),
            ],
        ),
    ]
