# Generated by Django 2.2 on 2019-04-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190421_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(default='#', max_length=200)),
                ('img', models.CharField(max_length=100)),
                ('create_time', models.CharField(max_length=20)),
                ('is_del', models.BooleanField(default=False)),
            ],
        ),
    ]
