# Generated by Django 2.2 on 2019-04-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tel',
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(default='男', max_length=10),
        ),
    ]
